/**
 * bzip2 + tar extraction tests (260816 local speech).
 *
 * Fixtures live in __fixtures__/ as base64 text, generated by CPython's bz2 /
 * tarfile (an independent implementation):
 *   - fixture-pattern.bz2: a ~257KB deterministic text pattern compressed at
 *     block size 1 (100k), so the stream carries MULTIPLE blocks — exercises
 *     block chaining, the combined CRC, and the block CRC per block.
 *   - fixture-pax.tar / fixture-gnu.tar: dir + binary file + a >100-char path
 *     in pax ('x' records) and GNU ('L' longname) flavors.
 */
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { describe, expect, it } from 'vitest';
import { bunzip2 } from './bzip2';
import { parseTar } from './tar';

function fixture(name: string): Uint8Array {
  const b64 = readFileSync(path.join(__dirname, '__fixtures__', name), 'utf8').trim();
  return new Uint8Array(Buffer.from(b64, 'base64'));
}

/** The same pattern fixture-pattern.bz2 was built from. */
function pattern(): Uint8Array {
  const parts: string[] = [];
  for (let i = 0; i < 4200; i += 1) {
    parts.push(`line-${String(i).padStart(6, '0')}: the quick brown fox jumps over the lazy dog ${i * 7}\n`);
  }
  return new Uint8Array(Buffer.from(parts.join(''), 'utf8'));
}

const LONG_NAME = `pack/${'sub/'.repeat(10)}${'x'.repeat(80)}.txt`;

describe('bunzip2', () => {
  it('round-trips a multi-block stream byte-exactly', () => {
    const out = bunzip2(fixture('fixture-pattern.bz2.b64'));
    const expected = pattern();
    expect(out.length).toBe(expected.length);
    expect(Buffer.from(out).equals(Buffer.from(expected))).toBe(true);
  });

  it('rejects garbage and truncation', () => {
    expect(() => bunzip2(new Uint8Array([1, 2, 3, 4]))).toThrow();
    const good = fixture('fixture-pattern.bz2.b64');
    expect(() => bunzip2(good.subarray(0, good.length - 40))).toThrow();
    const corrupt = good.slice();
    corrupt[2000] ^= 0xff; // flip bits mid-block → CRC or structure error
    expect(() => bunzip2(corrupt)).toThrow();
  });
});

describe('parseTar', () => {
  for (const flavor of ['pax', 'gnu'] as const) {
    it(`extracts dirs, files, and long names from a ${flavor} archive`, () => {
      const entries = parseTar(fixture(`fixture-${flavor}.tar.b64`));
      const dir = entries.find((e) => e.type === 'dir');
      expect(dir?.name.replace(/\/$/, '')).toBe('pack');
      const model = entries.find((e) => e.name === 'pack/model.onnx');
      expect(model?.type).toBe('file');
      expect(model?.data.length).toBe(1024);
      expect(model?.data[255]).toBe(255);
      const long = entries.find((e) => e.name === LONG_NAME);
      expect(long?.type).toBe('file');
      expect(Buffer.from(long?.data ?? new Uint8Array()).toString()).toBe('hello long name');
    });
  }
});
