/**
 * 260703 procgen — Unique-companion generation pipeline (MAIN process only).
 *
 * Orchestrates the full "Meet your unique companion" flow:
 *   soulcaster-1 character sheet  →  in PARALLEL { portrait (KusArt image gen) →
 *   img2skin skin } + persona expansion  →  save (kind 'unique', shared false).
 *
 * Cloud-mode + signed-in only: the character sheet + persona both stream through
 * the proxy's `/free` route. The portrait is generated by the KusArt B2B API
 * (X-API-Key, build-time KUSART_API_KEY) with a style_id chosen from the user's
 * art_style preference (see KUSART_STYLE_BY_ART_STYLE; default "Glossy Skin
 * Render Anime"). BYOK users cannot generate — they get `not_signed_in`.
 *
 * The pipeline NEVER throws for expected failures; it resolves the discriminated
 * `GenerateUniqueResult`. Stage progress is pushed via the injected `emit` sink
 * (the IPC handler tags each tick with the caller's requestId and forwards it on
 * IpcChannel.gen.progress — same shape as chars:expansion-progress).
 *
 * Ordering note (deviation from the literal spec, functionally identical): the
 * expensive parallel work (image gen + img2skin + persona expansion) runs
 * concurrently and only PRODUCES bytes/text; the store writes (saveCharacter →
 * applyPortrait → applyPng) are serialized AFTER the character JSON exists on
 * disk. applyPortrait / applyPng both `getCharacter` + `saveCharacter`, so they
 * require the row to exist — saving first and applying after avoids a
 * skeleton-write race between the two branches.
 */

import { randomUUID } from 'node:crypto';
import { createRequire } from 'node:module';
import { mkdtemp, writeFile, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import Anthropic from '@anthropic-ai/sdk';
import type {
  GenerateUniqueInput,
  GenerateUniqueResult,
  GenStage,
  UniqueGender,
} from '../shared/ipc';
import type {
  Character,
  CompanionDynamic,
  UserConfig,
  UserPreferences,
  UserPreferencesPatch,
} from '../shared/characterSchema';
import { COMPANION_DYNAMICS, MAX_COMPANION_SLOTS, PREF_QUESTIONS, countsAsHomeSlot } from '../shared/characterSchema';
import { PORTRAIT_MAX_BYTES, PORTRAIT_MAX_DIM } from './portraitImageUtil';
import { parsePngIhdr } from './skinImageUtil';

const PROXY_BASE_URL = process.env.SEI_PROXY_URL ?? 'https://api.sei.gg';

/**
 * KusArt B2B image generation (https://kusart.com/api-for-business).
 * Auth is a raw `X-API-Key` header; the key is injected at build time from
 * .env (KUSART_API_KEY, gitignored — see electron.vite.config.ts). Responses
 * use a code/message/data envelope where code 0 = success and business errors
 * may still arrive as HTTP 200.
 */
const KUSART_BASE_URL = process.env.KUSART_BASE_URL ?? 'https://api.kusa.pics';
const KUSART_API_KEY = process.env.KUSART_API_KEY ?? '';

/**
 * KusArt B2B `style_id` per user art_style preference. The numeric ids were
 * verified against the public style library (kusart.com/library/styles, each
 * style's detail page embeds its `styleId`) on 260706 — the id is the style's
 * 1-based position in that catalog:
 *
 *   art_style  | style_id | KusArt style name          | look
 *   -----------|----------|----------------------------|-------------------------------
 *   chibi      |    9     | Chibi Dot Eyes             | round chibi, oversized heads, dot eyes
 *   anime      |   15     | Glossy Skin Render Anime   | figure-quality glossy skin render (the historical default)
 *   celshaded  |   14     | Cel-Shaded Anime           | flat color blocks, crisp shadow edges (Genshin-like)
 *   cartoon    |   19     | Rough Outline Cartoon      | loose hand-drawn western-cartoon outlines
 *   3d         |   18     | VRChat Style               | 3D-meets-anime render (closest to a 3D figure)
 *   (null)     |   15     | -> anime                   | no preference falls back to the anime default
 *
 * The library is anime-first: there is no true photoreal-3D or Pixar-western
 * style, so `3d`→VRChat and `cartoon`→Rough Outline Cartoon are the nearest
 * matches, not exact genre hits. Revisit if KusArt adds dedicated styles.
 */
const KUSART_STYLE_BY_ART_STYLE: Record<NonNullable<UserPreferences['art_style']>, string> = {
  chibi: '9',
  anime: '15',
  celshaded: '14',
  cartoon: '19',
  '3d': '18',
};
/** Style used when the user has no art_style preference (null / never asked). */
const KUSART_STYLE_DEFAULT = '15';

/** Map the user's art_style preference to a KusArt style_id (anime fallback). */
function resolveKusartStyleId(artStyle: UserPreferences['art_style'] | null | undefined): string {
  return artStyle ? KUSART_STYLE_BY_ART_STYLE[artStyle] : KUSART_STYLE_DEFAULT;
}

/** Native request dimensions (tall 4:7 portrait, matches the zoom aspect). */
const KUSART_WIDTH = 960;
const KUSART_HEIGHT = 1680;
const KUSART_POLL_INTERVAL_MS = 2_000;

/** Model used for the soulcaster sheet consolidation call (proxy /free route). */
const SHEET_MODEL = 'claude-haiku-4-5';
const SHEET_TIMEOUT_MS = 60_000;
const IMAGE_TIMEOUT_MS = 60_000;
/** Overall wall-clock cap for the pipeline body (after the fast guards). */
const PIPELINE_CAP_MS = 150_000;

/** Progress sink: the IPC handler baked in the caller's requestId. */
export type GenEmit = (stage: GenStage, status: 'start' | 'done' | 'error', message?: string) => void;

/* -------------------------------------------------------------------------- */
/*  Pure helpers (unit-tested)                                                 */
/* -------------------------------------------------------------------------- */

/**
 * Number of Home companion slots the user currently occupies. MUST mirror the
 * renderer's Home/IconRail library filter, or the slot guard rejects on a
 * visibly non-full grid (and vice versa):
 *
 *   - bundled defaults (is_default) occupy a slot only when invited
 *     (config.added_default_ids);
 *   - FOREIGN-owned characters (owner set, !== current user) occupy a slot
 *     only when explicitly added from the World tab (config.added_world_ids).
 *     This matters because merely hovering/opening a World card caches the
 *     foreign row locally (charsOpenPrepare → ensureLocallyCached), so a bare
 *     `!is_default` count would inflate with every browse;
 *   - everything else (own + legacy null-owner local chars) always counts.
 */
export function libraryCharacterCount(
  characters: Pick<Character, 'id' | 'is_default' | 'owner'>[],
  config: { added_default_ids?: string[] | null; added_world_ids?: string[] | null },
  currentUserId: string | null = null,
): number {
  // ONE rule, shared with the renderer's isHomeCharacter via countsAsHomeSlot
  // (src/shared/characterSchema.ts) — the count and the visible Home grid must
  // agree. In particular, when signed out (currentUserId null) an owner-stamped
  // cached World row does NOT count (isHomeCharacter hides it), so browsing the
  // World tab can never inflate the slot count against an empty-looking grid.
  const addedDefaultIds = new Set(config.added_default_ids ?? []);
  const addedWorldIds = new Set(config.added_world_ids ?? []);
  let n = 0;
  for (const c of characters) {
    if (countsAsHomeSlot(c, { currentUserId, addedDefaultIds, addedWorldIds })) n += 1;
  }
  return n;
}

const EMPTY_PREFS: UserPreferences = {
  companion_age_range: null,
  art_style: null,
  companion_dynamics: null,
  completed_at: null,
};

/**
 * Which relationship dynamic the NEXT unique cast gets. Each RANKED
 * preference is granted exactly once, top pick first: the first ranking
 * entry not yet in `granted` (the device-local UserConfig.dynamics_granted
 * list, appended after a cast saves) wins. Once the ranking is exhausted —
 * or the user never ranked (`[]` Surprise me / null never-asked) — the cast
 * rolls a uniformly random dynamic. Every cast therefore has a dynamic;
 * deleting a companion never re-grants its preference (grants are per
 * relationship, not per slot).
 */
export function resolveDynamic(
  ranking: readonly CompanionDynamic[] | null | undefined,
  granted: readonly CompanionDynamic[] | null | undefined,
  rng: () => number = Math.random,
): CompanionDynamic {
  const grantedSet = new Set(granted ?? []);
  for (const d of ranking ?? []) {
    if (!grantedSet.has(d)) return d;
  }
  return COMPANION_DYNAMICS[Math.floor(rng() * COMPANION_DYNAMICS.length)] ?? COMPANION_DYNAMICS[0];
}

/**
 * Merge a questionnaire patch over the CURRENT stored answers, stamping
 * completed_at with `now`. Keys absent from the patch keep their stored
 * value (that's what makes "ask only the missing questions" safe); keys
 * present — including explicit nulls and the `[]` Surprise-me ranking — win.
 * Pure; the prefs:save handler runs it inside configStore.updateConfig so
 * the merge base is the freshly-locked config, not a renderer snapshot
 * (TOCTOU).
 */
export function mergePrefsPatch(
  current: UserPreferences | null | undefined,
  patch: UserPreferencesPatch,
  now: string,
): UserPreferences {
  const base: UserPreferences = current ?? { ...EMPTY_PREFS };
  const merged: UserPreferences = { ...base, completed_at: now };
  for (const key of PREF_QUESTIONS) {
    const value = patch[key];
    if (value !== undefined) {
      (merged as Record<string, unknown>)[key] = value;
    }
  }
  return merged;
}

/**
 * Reconcile the local (config.user_profile) and cloud (user_preferences row)
 * questionnaire copies. Cloud wins when it is NEWER — it carries a completed_at
 * that the local copy lacks, or a later completed_at.
 *
 *   - profile      — the effective profile to return to the renderer.
 *   - cloudIsNewer — true when the cloud copy should be written back into config.
 *   - hasCompleted — true when EITHER copy has a completed_at (drives `needed`:
 *                    the caller sets needed = signedIn && !hasCompleted).
 */
export function resolvePrefs(
  local: UserPreferences | null,
  cloud: UserPreferences | null,
): { profile: UserPreferences; cloudIsNewer: boolean; hasCompleted: boolean } {
  const localDone = !!local?.completed_at;
  const cloudDone = !!cloud?.completed_at;

  let cloudIsNewer = false;
  if (cloud && cloudDone) {
    if (!localDone) {
      cloudIsNewer = true;
    } else {
      const c = Date.parse(cloud.completed_at!);
      const l = Date.parse(local!.completed_at!);
      cloudIsNewer = Number.isFinite(c) && (!Number.isFinite(l) || c > l);
    }
  }

  const profile = cloudIsNewer
    ? cloud!
    : (local ?? cloud ?? EMPTY_PREFS);

  return { profile, cloudIsNewer, hasCompleted: localDone || cloudDone };
}

/** Trim a paragraph down to its first `maxSentences` sentences / `maxChars`. */
function condense(text: string, maxSentences: number, maxChars: number): string {
  const clean = String(text ?? '').replace(/\s+/g, ' ').trim();
  if (!clean) return '';
  const sentences = clean.match(/[^.!?]+[.!?]+/g) ?? [clean];
  let out = sentences.slice(0, maxSentences).join(' ').trim();
  if (out.length > maxChars) out = out.slice(0, maxChars).trimEnd() + '…';
  return out;
}

type Sheet = {
  name: string;
  gender: string;
  age: number;
  age_note: string | null;
  background: string;
  species_detail: string;
  personality: { tone: string; values: string[]; quirks: string[]; fears: string[] };
  backstory: string;
  /** 260705: who the character is to the player (soulcaster player_dynamic). */
  player_dynamic?: string | null;
  voice_style: string;
  /** ElevenLabs voice id from soulcaster's curated pool — stamped by castSoul
   * (never LLM-authored). Optional: sheets generated before voices existed
   * lack it; resolveVoiceId (voice/voiceAssign.ts) backfills those. */
  voice_id?: string;
  /**
   * 260705: texting register (soulcaster `punctuation`). 'casual' = normal
   * modern texting, no sentence-ending periods (most characters).
   * 'deliberate' = ends sentences with full stops on purpose. Promoted to
   * character.metadata.punctuation at save time; the bot + chat surfaces
   * enforce it mechanically. Optional: older sheets lack it (treated casual).
   */
  punctuation?: 'casual' | 'deliberate' | null;
  appearance: Record<string, unknown>;
  image_prompt: string;
  /**
   * 260705: soulcaster-authored card caption ("a wry wood elf cartographer") —
   * lowercase, name-free, 3-8 words. Preferred by buildDescription over the
   * client-side tone/species derivation. Optional: older sheets lack it.
   */
  card_line?: string | null;
};

/**
 * Build a compact appearance/outfit summary from the sheet's `appearance`
 * block, or '' when there's nothing usable (defensive; soulcaster's schema
 * requires these fields, but older sheets / test fixtures may omit them).
 *
 * 260704: the sheet's appearance (incl. `outfit`, a specific, prompt-enforced
 * garment description) was being generated but never reaching the character's
 * persona/description — the LLM playing the companion had no idea what it
 * wore. This folds outfit + hair/eyes/height/build + accessories/distinguishing
 * features into one terse line so both `expandPersona` and the bot's runtime
 * persona know what the character looks like and is wearing.
 */
function buildAppearanceSummary(appearance: Record<string, unknown> | null | undefined): string {
  const a = appearance ?? {};
  const str = (v: unknown): string => (typeof v === 'string' ? v.trim() : '');
  const list = (v: unknown): string[] =>
    Array.isArray(v) ? v.filter((x): x is string => typeof x === 'string' && x.trim().length > 0) : [];
  const sentence = (s: string): string => (s === '' || /[.…]$/.test(s) ? s : `${s}.`);

  const overall = condense(str(a.overall), 1, 160);
  const outfit = condense(str(a.outfit), 2, 280);
  const hair = str(a.hair);
  const eyes = str(a.eyes);
  const heightBuild = [str(a.height), str(a.build)].filter(Boolean).join(', ');
  const accessories = list(a.accessories);
  const features = list(a.distinguishing_features);

  const bits: string[] = [];
  if (overall) bits.push(sentence(overall));
  if (outfit) bits.push(sentence(`Wears: ${outfit}`));
  if (hair) bits.push(sentence(`Hair: ${hair}`));
  if (eyes) bits.push(sentence(`Eyes: ${eyes}`));
  if (heightBuild) bits.push(sentence(heightBuild));
  if (accessories.length) bits.push(sentence(`Accessories: ${accessories.slice(0, 3).join(', ')}`));
  if (features.length) bits.push(sentence(`Features: ${features.slice(0, 2).join(', ')}`));

  return bits.join(' ');
}

/**
 * Compose the persona `source` blurb the expander consumes — a compact readable
 * paragraph (NOT raw JSON) covering identity, personality, voice, appearance
 * (incl. outfit), and a condensed backstory.
 */
export function buildPersonaBlurb(sheet: Sheet): string {
  const p = sheet.personality;
  const ageBit = sheet.age_note ? `${sheet.age} (${sheet.age_note})` : `${sheet.age}`;
  const species = sheet.species_detail || sheet.background;
  const appearanceSummary = buildAppearanceSummary(sheet.appearance);
  const playerDynamic = String(sheet.player_dynamic ?? '').trim();
  const lines = [
    `${sheet.name}, ${species}, age ${ageBit}.`,
    `Tone: ${sheet.personality.tone}`,
    `Values: ${(p.values ?? []).join(', ')}`,
    `Quirks: ${(p.quirks ?? []).join(', ')}`,
    `Fears: ${(p.fears ?? []).join(', ')}`,
    ...(playerDynamic ? [`With the player: ${playerDynamic}`] : []),
    `Voice: ${sheet.voice_style}`,
    // Deliberate texters carry the register into the expansion so the VOICE
    // section + sample lines come out period-terminated. Casual is the default
    // everywhere (runtime chat directive + period strip), so it adds no line.
    ...(sheet.punctuation === 'deliberate'
      ? ['Texting style: ends every sentence with a period, flat and deliberate, even in relaxed chat.']
      : []),
    ...(appearanceSummary ? [`Appearance: ${appearanceSummary}`] : []),
    `Backstory: ${condense(sheet.backstory, 4, 600)}`,
  ];
  return lines.join('\n');
}

/**
 * Compact species tag for the identity line. `species_detail` is NOT safe to
 * show raw: for humans it is an appearance description by contract
 * (soulcaster prompt.js: "describe skin tone and any notable human
 * features"), and for other backgrounds it can run long ("fox-person with
 * tall russet ears and a full brush tail"). Humans are always just "human";
 * other backgrounds keep the leading noun phrase of the detail ("wood elf",
 * "porcelain automaton") and fall back to the background word.
 */
function speciesTag(sheet: Sheet): string {
  if (sheet.background === 'human') return 'human';
  const name = String(sheet.name ?? '').trim();
  let head = String(sheet.species_detail ?? '')
    .split(/[,;.]|\bwith\b/)[0]
    .trim();
  // Some sheets return a full sentence ("Anaya is a wolf-person"): strip the
  // "<Name> is a/an" lead-in and any bare article so the tag reads as a noun
  // phrase after "a".
  if (name) head = head.replace(new RegExp(`^${escapeRegExp(name)}\\s+(?:is|was)\\s+`, 'i'), '');
  head = head.replace(/^(?:a|an|the)\s+/i, '').trim();
  // A tag still carrying the character's name is a sentence fragment, not a
  // species — fall back to the background word.
  const nameLeak = !!name && head.toLowerCase().includes(name.toLowerCase());
  const tag = head && head.length <= 32 && !nameLeak ? head : sheet.background;
  // Sheets sometimes capitalize ("Android chassis") — lowercase mid-sentence.
  return tag.charAt(0).toLowerCase() + tag.slice(1);
}

/** Escape a string for literal use inside a RegExp. */
function escapeRegExp(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/**
 * User-facing `description`: a single-sentence identity summary — name,
 * surface tone, species tag. Deliberately EXCLUDES the backstory and all
 * appearance detail (260705 user direction): the description shows on
 * Home/World cards, and who the character is beyond a one-line identity is
 * meant to be discovered through play, not read off a card. The full
 * backstory + appearance still reach the persona via buildPersonaBlurb.
 */
export function buildDescription(sheet: Sheet): string {
  // Preferred path (260705): soulcaster now authors the caption directly as
  // `card_line` ("a wry wood elf cartographer") — one writer, no parsing.
  // Light sanitation only: collapse whitespace, strip a leading name the
  // model was told not to include, strip dashes and a trailing period.
  const name = String(sheet.name ?? '').trim();
  let card = String(sheet.card_line ?? '')
    .replace(/\s*[—–]\s*/g, ', ')
    .replace(/\s+/g, ' ')
    .trim()
    .replace(/[.\s]+$/, '');
  if (name) card = card.replace(new RegExp(`^${escapeRegExp(name)},?\\s+`, 'i'), '');
  if (card) {
    const desc = `${name}, ${card.charAt(0).toLowerCase()}${card.slice(1)}.`;
    return desc.length > 120 ? desc.slice(0, 120).trimEnd() + '…' : desc;
  }
  // Fallback for sheets without card_line: derive from tone + species_detail.
  return derivedDescription(sheet);
}

/** Pre-card_line derivation, kept as the fallback for older sheets. */
function derivedDescription(sheet: Sheet): string {
  // Tones can be long compounds ("sardonic and calculating; quick to joke
  // about circumstances but…") — keep only the first clause, and only when
  // it stays short. Some sheets also return sentence-style tones ("Anaya
  // speaks with unhurried calm"): strip a leading name, and drop the clause
  // entirely when it reads as a sentence (starts with a verb or still names
  // the character) — "a speaks with unhurried calm wolf-person" is garbage.
  const name = String(sheet.name ?? '').trim();
  let toneClause = String(sheet.personality?.tone ?? '')
    .split(/[,;.]/)[0]
    .trim();
  if (name) toneClause = toneClause.replace(new RegExp(`^${escapeRegExp(name)}\\s+`, 'i'), '');
  if (
    /^(?:is|was|has|had|speaks|talks|tends|likes|loves|often|always|usually|carries)\b/i.test(toneClause) ||
    (name && toneClause.toLowerCase().includes(name.toLowerCase()))
  ) {
    toneClause = '';
  }
  // Sheets sometimes capitalize the tone ("Direct and candid"); mid-sentence it
  // reads better lowercased.
  toneClause = toneClause.charAt(0).toLowerCase() + toneClause.slice(1);
  const tone = toneClause && toneClause.length <= 40 ? `${toneClause} ` : '';
  // Strip em/en dashes the same way the card_line path does — an LLM-authored
  // tone ("warm - but guarded") must not ship a dash into user-facing copy.
  const desc = `${sheet.name}, a ${tone}${speciesTag(sheet)}.`.replace(/\s*[—–]\s*/g, ', ');
  return desc.length > 120 ? desc.slice(0, 120).trimEnd() + '…' : desc;
}

/* -------------------------------------------------------------------------- */
/*  Runtime deps (image processing loaded lazily / defensively)               */
/* -------------------------------------------------------------------------- */

/** Minimal fluent slice of sharp's API (every op returns the same instance). */
interface SharpChain {
  resize(opts: {
    width: number;
    height: number;
    fit: 'inside' | 'fill';
    withoutEnlargement?: boolean;
  }): SharpChain;
  extract(region: { left: number; top: number; width: number; height: number }): SharpChain;
  extend(opts: { top: number; extendWith: 'copy' }): SharpChain;
  composite(layers: Array<{ input: Buffer; top: number; left: number }>): SharpChain;
  greyscale(): SharpChain;
  raw(): SharpChain;
  png(opts?: { compressionLevel?: number; palette?: boolean; colors?: number; quality?: number }): SharpChain;
  toBuffer(): Promise<Buffer>;
}

interface SharpLike {
  (input: Buffer): SharpChain;
}

let _sharp: SharpLike | null | undefined;

/**
 * Load sharp WITHOUT taking a direct dependency on it: sharp ships as a
 * transitive dep of img2skin (which the skin pipeline resolves the same way).
 * Resolved from the img2skin package directory so it works in dev and in
 * asar-unpacked packaged builds. Returns null when sharp is unavailable — the
 * caller then only applies an already-compliant portrait.
 */
function loadSharp(): SharpLike | null {
  if (_sharp !== undefined) return _sharp;
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  const req = typeof require === 'function' ? require : createRequire(process.cwd() + '/');
  const tries: Array<() => string> = [
    () => req.resolve('sharp', { paths: [path.dirname(req.resolve('img2skin/package.json'))] }),
    () => req.resolve('sharp'),
  ];
  for (const resolve of tries) {
    try {
      _sharp = req(resolve()) as SharpLike;
      return _sharp;
    } catch {
      /* try next */
    }
  }
  _sharp = null;
  return _sharp;
}

/**
 * Coerce arbitrary generated PNG bytes into the portrait pipeline's constraints
 * (≤PORTRAIT_MAX_DIM² and ≤PORTRAIT_MAX_BYTES) so applyPortrait's validation
 * accepts them. Uses sharp (via img2skin) to progressively downscale + palette-
 * compress; falls back to the raw bytes only when they are already compliant.
 */
async function toCompliantPortraitPng(bytes: Buffer): Promise<Buffer> {
  let dims: { width: number; height: number } | null = null;
  try {
    dims = parsePngIhdr(bytes);
  } catch {
    dims = null;
  }
  const alreadyOk =
    bytes.length <= PORTRAIT_MAX_BYTES &&
    dims != null &&
    dims.width <= PORTRAIT_MAX_DIM &&
    dims.height <= PORTRAIT_MAX_DIM;
  if (alreadyOk) return bytes;

  const sharp = loadSharp();
  if (!sharp) {
    throw new Error('portrait exceeds limits and image processing (sharp) is unavailable');
  }
  for (const size of [PORTRAIT_MAX_DIM, 896, 768, 640, 512]) {
    const out = await sharp(bytes)
      .resize({ width: size, height: size, fit: 'inside', withoutEnlargement: true })
      .png({ compressionLevel: 9, palette: true, quality: 90 })
      .toBuffer();
    if (out.length <= PORTRAIT_MAX_BYTES) return out;
  }
  // Last resort — aggressive palette reduction at the smallest size.
  return await sharp(bytes)
    .resize({ width: 512, height: 512, fit: 'inside', withoutEnlargement: true })
    .png({ compressionLevel: 9, palette: true, colors: 128, quality: 70 })
    .toBuffer();
}

/** Downscale width for the focus-energy map (grayscale, aspect preserved). */
const ZOOM_DOWNSCALE_W = 240;
/** Character is framed to occupy this fraction of the crop's height. */
const ZOOM_TARGET_FILL = 0.75;
/** Output aspect (matches KusArt 960x1680 = 4:7) so the tall portrait shape is kept. */
const ZOOM_ASPECT_W = 4;
const ZOOM_ASPECT_H = 7;
/**
 * Full-standing-figure rescue (260705, calibrated on real outputs): a bbox
 * taller than this h/w ratio is a full-body render (Anaya, wolf-person: 2.74)
 * rather than a compliant waist-up one (android 2.00, scholar 1.75). Those
 * can't be framed whole at 75% fill (the window would exceed the image), so
 * instead crop to the upper body: the head+torso is taken as the top
 * TORSO_FRAC of the figure, framed at the normal target fill with a little
 * headroom above the bbox top.
 */
const ZOOM_FULLBODY_MIN_HW = 2.4;
const ZOOM_FULLBODY_TORSO_FRAC = 0.55;
const ZOOM_FULLBODY_HEADROOM = 0.08;

/**
 * From a downscaled grayscale raster, estimate the in-focus character's
 * bounding box as normalized [0,1] fractions of the frame, or null when the
 * detector is not confident.
 *
 * Change 3 blurs the background and keeps the character in sharp focus, so
 * high-frequency (edge) energy concentrates on the character. This computes a
 * 3x3 Laplacian energy map, grids it, thresholds cells relative to the peak,
 * rejects speckle (cells without >=2 active neighbours), and takes the bbox of
 * what survives. Confidence gates reject implausible or low-separation results.
 *
 * Pure (no sharp) so it is unit-testable on a synthetic raster.
 */
export function estimateCharacterBBox(
  gray: Uint8Array | Buffer,
  w: number,
  h: number,
  channels: number,
): { left: number; top: number; width: number; height: number } | null {
  if (w < 16 || h < 16 || channels < 1) return null;
  const L = (x: number, y: number): number => gray[(y * w + x) * channels];

  // Grid the frame into ~30 columns of square cells.
  const cell = Math.max(2, Math.floor(w / 30));
  const gw = Math.floor(w / cell);
  const gh = Math.floor(h / cell);
  if (gw < 4 || gh < 4) return null;

  // Accumulate mean |Laplacian| per cell over interior pixels.
  const energy = new Float64Array(gw * gh);
  const count = new Float64Array(gw * gh);
  for (let y = 1; y < h - 1; y++) {
    const gy = Math.floor(y / cell);
    if (gy >= gh) continue;
    for (let x = 1; x < w - 1; x++) {
      const gx = Math.floor(x / cell);
      if (gx >= gw) continue;
      const lap = Math.abs(4 * L(x, y) - L(x - 1, y) - L(x + 1, y) - L(x, y - 1) - L(x, y + 1));
      const gi = gy * gw + gx;
      energy[gi] += lap;
      count[gi] += 1;
    }
  }
  let maxE = 0;
  for (let i = 0; i < energy.length; i++) {
    if (count[i] > 0) energy[i] /= count[i];
    if (energy[i] > maxE) maxE = energy[i];
  }
  // Flat / uniformly-blurred frame: nothing in focus to crop to.
  if (maxE < 6) return null;

  // Energy separation gate: the focused subject must stand clear of the
  // background. If the peak barely beats the median, the whole frame is
  // textured (blur did not take) — don't trust the bbox.
  const sorted = Float64Array.from(energy).sort();
  const median = sorted[Math.floor(sorted.length / 2)] || 0;
  if (median > 0 && maxE < 1.6 * median) return null;

  const thresh = 0.18 * maxE;
  const active = new Uint8Array(gw * gh);
  for (let i = 0; i < energy.length; i++) active[i] = energy[i] >= thresh ? 1 : 0;

  // Speckle rejection: keep an active cell only if >=2 of its 8-neighbours
  // are also active (isolated hot cells are background grain / JPEG noise).
  const kept = new Uint8Array(gw * gh);
  let keptCount = 0;
  for (let gy = 0; gy < gh; gy++) {
    for (let gx = 0; gx < gw; gx++) {
      if (!active[gy * gw + gx]) continue;
      let n = 0;
      for (let dy = -1; dy <= 1; dy++) {
        for (let dx = -1; dx <= 1; dx++) {
          if (dx === 0 && dy === 0) continue;
          const nx = gx + dx;
          const ny = gy + dy;
          if (nx >= 0 && nx < gw && ny >= 0 && ny < gh && active[ny * gw + nx]) n++;
        }
      }
      if (n >= 2) {
        kept[gy * gw + gx] = 1;
        keptCount++;
      }
    }
  }
  // Too little structure survived — no confident subject.
  if (keptCount < Math.max(3, Math.round(0.02 * gw * gh))) return null;

  let gx0 = gw;
  let gy0 = gh;
  let gx1 = -1;
  let gy1 = -1;
  for (let gy = 0; gy < gh; gy++) {
    for (let gx = 0; gx < gw; gx++) {
      if (!kept[gy * gw + gx]) continue;
      if (gx < gx0) gx0 = gx;
      if (gx > gx1) gx1 = gx;
      if (gy < gy0) gy0 = gy;
      if (gy > gy1) gy1 = gy;
    }
  }
  if (gx1 < gx0 || gy1 < gy0) return null;

  // Map grid bbox to pixel span, then to normalized fractions.
  const px0 = gx0 * cell;
  const py0 = gy0 * cell;
  const px1 = Math.min(w, (gx1 + 1) * cell);
  const py1 = Math.min(h, (gy1 + 1) * cell);
  const left = px0 / w;
  const top = py0 / h;
  const width = (px1 - px0) / w;
  const height = (py1 - py0) / h;

  // Plausibility gates on the normalized bbox.
  const area = width * height;
  if (width <= 0 || height <= 0) return null;
  if (area < 0.05 || area > 0.95) return null;

  return { left, top, width, height };
}

/**
 * From a subject bbox (pixels) inside a WxH frame, compute the crop window that
 * frames the subject at ZOOM_TARGET_FILL of the crop height, aspect-locked to
 * ZOOM_ASPECT_W:ZOOM_ASPECT_H and centered on the bbox (clamped to bounds).
 * Returns null when the crop would need to upscale (the subject already fills
 * the frame) — the caller then no-ops. Pure + unit-tested.
 */
export function computeCropWindow(
  bbox: { left: number; top: number; width: number; height: number },
  imageW: number,
  imageH: number,
  opts: { targetFill?: number; aspectW?: number; aspectH?: number } = {},
): { left: number; top: number; width: number; height: number } | null {
  const targetFill = opts.targetFill ?? ZOOM_TARGET_FILL;
  const aspectW = opts.aspectW ?? ZOOM_ASPECT_W;
  const aspectH = opts.aspectH ?? ZOOM_ASPECT_H;
  if (bbox.width <= 0 || bbox.height <= 0 || imageW <= 0 || imageH <= 0) return null;

  const winH = Math.round(bbox.height / targetFill);
  const winW = Math.round((winH * aspectW) / aspectH);
  // Never upscale: a window that can't fit inside the frame means the subject
  // already fills it. Before giving up, check for a full standing figure (tall
  // narrow bbox): those fill the height but leave the face tiny, so rescue by
  // cropping to the upper body instead of no-opping.
  if (winH >= imageH || winW >= imageW || winH < 8 || winW < 8) {
    if (bbox.height / bbox.width >= ZOOM_FULLBODY_MIN_HW) {
      const upperH = Math.round((bbox.height * ZOOM_FULLBODY_TORSO_FRAC) / targetFill);
      const upperW = Math.round((upperH * aspectW) / aspectH);
      if (upperH < imageH && upperW < imageW && upperH >= 8 && upperW >= 8) {
        const cx = bbox.left + bbox.width / 2;
        let left = Math.round(cx - upperW / 2);
        // Anchor at the figure's top (the head), with a little headroom.
        let top = Math.round(bbox.top - ZOOM_FULLBODY_HEADROOM * upperH);
        left = Math.max(0, Math.min(left, imageW - upperW));
        top = Math.max(0, Math.min(top, imageH - upperH));
        return { left, top, width: upperW, height: upperH };
      }
    }
    return null;
  }

  const cx = bbox.left + bbox.width / 2;
  const cy = bbox.top + bbox.height / 2;
  let left = Math.round(cx - winW / 2);
  let top = Math.round(cy - winH / 2);
  left = Math.max(0, Math.min(left, imageW - winW));
  top = Math.max(0, Math.min(top, imageH - winH));
  return { left, top, width: winW, height: winH };
}

/**
 * Deterministic zoom-crop (260705, replaces the old lower-two-thirds compose):
 * frame the character at ~75% of the portrait height. Prompt framing alone hit
 * ~50% adherence, so the size is enforced here. The Change-3 prompt keeps the
 * character in sharp focus over a blurred background; this detects that focus
 * energy (see estimateCharacterBBox), then crops to computeCropWindow.
 *
 * Best-effort throughout: sharp unavailable, decode error, or a non-confident
 * detection all return the original bytes unchanged. Never upscales.
 */
async function zoomToCharacter(bytes: Buffer): Promise<Buffer> {
  try {
    const sharp = loadSharp();
    if (!sharp) return bytes;
    const dims = parsePngIhdr(bytes);
    if (!dims || dims.width < 64 || dims.height < 64) return bytes;

    const dw = ZOOM_DOWNSCALE_W;
    const dh = Math.max(16, Math.round((dw * dims.height) / dims.width));
    const gray = await sharp(bytes)
      .resize({ width: dw, height: dh, fit: 'fill' })
      .greyscale()
      .raw()
      .toBuffer();
    const channels = Math.max(1, Math.round(gray.length / (dw * dh)));

    const norm = estimateCharacterBBox(gray, dw, dh, channels);
    if (!norm) return bytes;

    const bboxPx = {
      left: Math.round(norm.left * dims.width),
      top: Math.round(norm.top * dims.height),
      width: Math.round(norm.width * dims.width),
      height: Math.round(norm.height * dims.height),
    };
    const win = computeCropWindow(bboxPx, dims.width, dims.height);
    if (!win) return bytes;

    return await sharp(bytes).extract(win).png().toBuffer();
  } catch (err) {
    console.warn(`[sei] zoomToCharacter failed, using uncropped image: ${(err as Error).message}`);
    return bytes;
  }
}

/**
 * POST the proxy's img2skin panel endpoint (260705): one Gemini image-to-image
 * call that renders the character as front+back orthographic Minecraft
 * pixel-art views on magenta (img2skin Branch B stage 1). The prompt is
 * server-owned; we only send the portrait bytes. Returns the raw panel-atlas
 * PNG. 60s wall-clock timeout via AbortController, mirrors generatePortraitPng.
 */
async function generatePanelAtlasPng(rawPng: Buffer, jwt: string): Promise<Buffer> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), IMAGE_TIMEOUT_MS);
  try {
    const resp = await fetch(`${PROXY_BASE_URL}/generate/skin`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${jwt}`,
      },
      body: JSON.stringify({ character_png_base64: rawPng.toString('base64') }),
      signal: controller.signal,
    });
    if (!resp.ok) {
      throw new Error(`skin panel generation failed: HTTP ${resp.status}`);
    }
    const json = (await resp.json()) as { png_base64?: unknown };
    const b64 = json?.png_base64;
    if (typeof b64 !== 'string' || b64.length === 0) {
      throw new Error('skin panel generation failed: response missing png_base64');
    }
    return Buffer.from(b64, 'base64');
  } finally {
    clearTimeout(timer);
  }
}

/**
 * Turn a full-body character PNG into a valid 64×64 Minecraft skin via
 * img2skin. 260705: tries the real Branch-B 'panel' pipeline first — the proxy
 * runs the one Gemini call (POST /generate/skin, skin_daily 4/day), and
 * img2skin maps the returned panel atlas to a skin locally via `mockAtlas`
 * (which skips its own direct-Gemini call — the client has no Google key).
 * Any failure (proxy down, gate 429, invalid panel geometry, validation
 * misses) falls back to the deterministic no-LLM painter branch, so every
 * input still yields a valid skin. Writes the source + reads the skin through
 * a scratch temp dir that is always cleaned up.
 *
 * `variant` selects the Minecraft skin model geometry — 'slim' (Alex, narrow
 * arms) vs 'classic' (Steve, wide arms). The bot serves skins via
 * CustomSkinLoader with model "auto", which detects slim vs classic from the
 * PNG's arm-region geometry, so passing the right variant here is what makes
 * female companions actually render as slim in-game (no schema/server change
 * needed).
 */
async function rawPngToSkin(
  rawPng: Buffer,
  variant: 'slim' | 'classic',
  jwt: string,
): Promise<Buffer> {
  const dir = await mkdtemp(path.join(tmpdir(), 'sei-skin-'));
  const src = path.join(dir, 'character.png');
  const out = path.join(dir, 'skin.png');
  try {
    await writeFile(src, rawPng);
    const { characterToSkin } = await import('img2skin/src/pipeline.js');
    try {
      const atlas = path.join(dir, 'panel.png');
      await writeFile(atlas, await generatePanelAtlasPng(rawPng, jwt));
      const res = await characterToSkin(src, out, { branch: 'panel', mockAtlas: atlas, variant });
      if (res.valid !== true) {
        throw new Error('panel-branch skin failed validation');
      }
      return await readFile(out);
    } catch (err) {
      console.warn(
        `[sei] img2skin panel branch failed, using fallback painter: ${(err as Error).message}`,
      );
    }
    await characterToSkin(src, out, { branch: 'fallback', variant });
    return await readFile(out);
  } finally {
    await rm(dir, { recursive: true, force: true }).catch(() => {});
  }
}

/** KusArt task result payload (subset we consume). */
interface KusartTaskData {
  task_id?: unknown;
  status?: unknown;
  error_message?: unknown;
  result?: {
    images?: Array<{ display_url?: unknown }>;
  } | null;
}

/**
 * `get_result` responds with this business code while the task is still
 * processing ("Task is not yet completed") — it is a normal polling state,
 * NOT a failure. Discovered live 260705: treating it as fatal made every
 * cast's first poll (2s in, render takes ~10-25s) kill the portrait branch.
 */
const KUSART_CODE_TASK_RUNNING = 41006;

/**
 * POST a KusArt B2B route and unwrap the code/message/data envelope.
 * Business errors can arrive as HTTP 200 with a non-zero `code`, so both
 * layers are checked. Codes listed in `pendingCodes` are tolerated and
 * surface as a synthetic PENDING task so the polling loop keeps waiting.
 */
async function kusartPost(
  pathname: string,
  body: unknown,
  signal: AbortSignal,
  pendingCodes: readonly number[] = [],
): Promise<KusartTaskData> {
  const resp = await fetch(`${KUSART_BASE_URL}${pathname}`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'X-API-Key': KUSART_API_KEY,
    },
    body: JSON.stringify(body),
    signal,
  });
  if (!resp.ok) {
    throw new Error(`image generation failed: HTTP ${resp.status} (${pathname})`);
  }
  const json = (await resp.json()) as { code?: unknown; message?: unknown; data?: KusartTaskData };
  if (json?.code !== 0) {
    if (typeof json?.code === 'number' && pendingCodes.includes(json.code)) {
      return { status: 'PENDING' };
    }
    throw new Error(`image generation failed: kusart code ${json?.code} ${json?.message ?? ''}`.trimEnd());
  }
  return json.data ?? {};
}

/** Abortable sleep for the polling loop (rejects when the deadline fires). */
function sleepAbortable(ms: number, signal: AbortSignal): Promise<void> {
  return new Promise((resolve, reject) => {
    const onAbort = (): void => {
      clearTimeout(timer);
      reject(new Error('image generation timed out'));
    };
    const timer = setTimeout(() => {
      signal.removeEventListener('abort', onAbort);
      resolve();
    }, ms);
    signal.addEventListener('abort', onAbort, { once: true });
  });
}

/**
 * Generate the portrait via the KusArt B2B API: create a TEXT_TO_IMAGE task
 * with the caller-selected `styleId` (mapped from the user's art_style
 * preference via resolveKusartStyleId), poll /tasks/get_result until COMPLETED,
 * then download the CDN image. Returns the raw PNG bytes. IMAGE_TIMEOUT_MS
 * wall-clock cap over the whole create → poll → download sequence via one
 * AbortController.
 */
async function generatePortraitPng(prompt: string, styleId: string): Promise<Buffer> {
  if (!KUSART_API_KEY) {
    throw new Error('image generation failed: KUSART_API_KEY is not configured');
  }
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), IMAGE_TIMEOUT_MS);
  try {
    const created = await kusartPost(
      '/api/go/b2b/tasks/create',
      {
        task_type: 'TEXT_TO_IMAGE',
        params: {
          prompt,
          style_id: styleId,
          width: KUSART_WIDTH,
          height: KUSART_HEIGHT,
          amount: 1,
          watermark: false,
        },
      },
      controller.signal,
    );
    const taskId = created.task_id;
    if (typeof taskId !== 'string' || taskId.length === 0) {
      throw new Error('image generation failed: kusart create returned no task_id');
    }

    // Poll until final. `create` may already carry a result for synchronous
    // completions, so check before the first sleep.
    let task: KusartTaskData = created;
    while (String(task.status ?? 'PENDING') !== 'COMPLETED') {
      if (String(task.status) === 'FAILED') {
        const reason = typeof task.error_message === 'string' && task.error_message ? task.error_message : 'task failed';
        throw new Error(`image generation failed: ${reason}`);
      }
      await sleepAbortable(KUSART_POLL_INTERVAL_MS, controller.signal);
      task = await kusartPost('/api/go/b2b/tasks/get_result', { task_id: taskId }, controller.signal, [
        KUSART_CODE_TASK_RUNNING,
      ]);
    }

    const url = task.result?.images?.[0]?.display_url;
    if (typeof url !== 'string' || url.length === 0) {
      throw new Error('image generation failed: kusart result missing image URL');
    }
    const imgResp = await fetch(url, { signal: controller.signal });
    if (!imgResp.ok) {
      throw new Error(`image generation failed: image download HTTP ${imgResp.status}`);
    }
    return Buffer.from(await imgResp.arrayBuffer());
  } finally {
    clearTimeout(timer);
  }
}

/**
 * Build the soulcaster `llm` sink — an Anthropic call over the proxy's /free
 * route (mirrors personaExpansion's cloud wiring). Non-streaming; returns the
 * model's raw text for soulcaster to parse + validate.
 */
function buildSoulcasterLlm(jwt: string): (args: {
  system: string;
  user: string;
  maxTokens?: number;
}) => Promise<string> {
  // apiKey:null → no X-Api-Key header, only Authorization: Bearer <jwt>.
  const client = new Anthropic({
    baseURL: `${PROXY_BASE_URL}/free`,
    authToken: jwt,
    apiKey: null,
    maxRetries: 0,
  });
  return async ({ system, user, maxTokens }) => {
    const resp = await client.messages.create(
      {
        model: SHEET_MODEL,
        max_tokens: maxTokens ?? 4096,
        system,
        messages: [{ role: 'user', content: user }],
      },
      { timeout: SHEET_TIMEOUT_MS },
    );
    // Duck-type the first text block out of the response content (avoids
    // coupling to a specific SDK content-block union export).
    const content = (resp as { content?: unknown }).content;
    if (Array.isArray(content)) {
      for (const b of content) {
        if (
          b != null &&
          typeof b === 'object' &&
          (b as { type?: unknown }).type === 'text' &&
          typeof (b as { text?: unknown }).text === 'string'
        ) {
          return (b as { text: string }).text;
        }
      }
    }
    return '';
  };
}

/** Classify an error into a network vs. generic generation failure. */
function classifyGenError(err: unknown): 'network' | 'generation_failed' {
  const msg = (err instanceof Error ? err.message : String(err)).toLowerCase();
  if (/enotfound|enetunreach|getaddrinfo|dns|econnrefused|econnreset|offline|fetch failed|network|timed? ?out|aborted/i.test(msg)) {
    return 'network';
  }
  return 'generation_failed';
}

/* -------------------------------------------------------------------------- */
/*  Orchestrator                                                              */
/* -------------------------------------------------------------------------- */

export interface GenerateUniqueDeps {
  /** Stage-progress sink (requestId already baked in by the caller). */
  emit: GenEmit;
}

export async function generateUnique(
  input: GenerateUniqueInput,
  deps: GenerateUniqueDeps,
): Promise<GenerateUniqueResult> {
  const { emit } = deps;
  const gender: UniqueGender = input.gender;

  // ── Guard 1: signed-in + cloud backend ─────────────────────────────────
  const { getAiBackendKind } = await import('./apiKeyStore');
  const { getClient } = await import('./auth/supabaseClient');
  const backendKind = await getAiBackendKind();
  const session = (await getClient().auth.getSession()).data.session;
  const jwt = session?.access_token ?? null;
  const userId = session?.user?.id ?? null;
  if (!jwt || !userId) {
    return { ok: false, code: 'not_signed_in', message: 'Sign in to generate a unique companion.' };
  }
  if (backendKind !== 'cloud-proxy') {
    return {
      ok: false,
      code: 'not_signed_in',
      message: 'Switch to managed billing (cloud) to generate a unique companion.',
    };
  }

  // ── Guard 2: slot limit ────────────────────────────────────────────────
  const { loadConfig } = await import('./configStore');
  const { listCharacters } = await import('./characterStore');
  const config = await loadConfig();
  const characters = await listCharacters();
  if (libraryCharacterCount(characters, config, userId) >= MAX_COMPANION_SLOTS) {
    return {
      ok: false,
      code: 'slot_limit',
      message: `You can only have ${MAX_COMPANION_SLOTS} companions. Remove one to make room.`,
    };
  }

  // ── Guard 3: daily creation quota ──────────────────────────────────────
  const { checkCreateQuota } = await import('./characterStore');
  const quota = await checkCreateQuota();
  if (quota.blocked) {
    return {
      ok: false,
      code: 'daily_limit',
      message: 'Daily creation limit reached. Come back tomorrow to make another companion.',
    };
  }

  // Relationship dynamic for THIS cast: first not-yet-granted ranked
  // preference, else random (see resolveDynamic). The grant is recorded in
  // config.dynamics_granted after the cast SAVES — a failed generation must
  // not consume the preference.
  const dynamic = resolveDynamic(config.user_profile?.companion_dynamics, config.dynamics_granted);

  // Everything past the guards is bounded by the wall-clock cap. The cap ABORTS
  // the pipeline (checked before the save step) — a timed-out run must never
  // save an orphan companion the user was told failed, or a "Try again" would
  // mint a duplicate into a slot the orphan already consumed.
  const cap = new AbortController();
  const pipeline = runPipeline({ gender, dynamic, jwt, userId, config, emit, signal: cap.signal });
  let capTimer: ReturnType<typeof setTimeout> | undefined;
  const capped = new Promise<GenerateUniqueResult>((resolve) => {
    capTimer = setTimeout(() => {
      cap.abort();
      resolve({ ok: false, code: 'generation_failed', message: 'Generation timed out. Please try again.' });
    }, PIPELINE_CAP_MS);
  });
  try {
    return await Promise.race([pipeline, capped]);
  } finally {
    clearTimeout(capTimer);
  }
}

async function runPipeline(args: {
  gender: UniqueGender;
  /** Relationship dynamic for this cast (resolveDynamic) — always set. */
  dynamic: CompanionDynamic;
  jwt: string;
  userId: string;
  config: UserConfig;
  emit: GenEmit;
  /** Set by the wall-clock cap: once aborted, the pipeline must not save. */
  signal: AbortSignal;
}): Promise<GenerateUniqueResult> {
  const { gender, dynamic, jwt, userId, config, emit, signal } = args;

  // ── Stage 'sheet' — soulcaster consolidation ───────────────────────────
  let sheet: Sheet;
  emit('sheet', 'start');
  try {
    const { castSoul } = await import('soulcaster');
    // Voice roll (260705): exclude voices the library already uses so a
    // roster's companions rarely share a voice. Best-effort — an unreadable
    // library just means no exclusions.
    let takenVoiceIds: string[] = [];
    try {
      const { listCharacters } = await import('./characterStore');
      const { assignedVoiceId } = await import('./voice/voiceAssign');
      takenVoiceIds = (await listCharacters())
        .map((c) => assignedVoiceId(c))
        .filter((v): v is string => v !== null);
    } catch {}
    const { sheet: cast } = await castSoul({
      gender,
      dynamic,
      userProfile: config.user_profile ?? null,
      takenVoiceIds,
      llm: buildSoulcasterLlm(jwt),
    });
    sheet = cast as Sheet;
    emit('sheet', 'done');
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    emit('sheet', 'error', msg);
    return { ok: false, code: classifyGenError(err), message: `Couldn't create the character sheet: ${msg}` };
  }

  const blurb = buildPersonaBlurb(sheet);
  const description = buildDescription(sheet);
  // Art style comes from the KusArt style_id (chosen from the user's onboarding
  // art_style preference), never from style text in the prompt.
  const styleId = resolveKusartStyleId(config.user_profile?.art_style);
  // The fixed suffix is A/B-tested (260705): "one character" suppresses
  // multi-figure compositions, and "reference sheet" phrasing must NEVER be
  // used (it triggers multi-view turnaround grids). Framing wording is aimed
  // deliberately WIDE (260705 iteration): the earlier "close waist-up portrait,
  // fills most of the frame" OVERSHOT into extreme face close-ups with the top
  // of the head cropped off — unrecoverable, since zoomToCharacter can tighten a
  // too-small subject but nothing can restore a head cut by the frame edge. The
  // current wording ("medium shot from the waist up", "the entire head is fully
  // visible with empty space above the head", "not a close up of the face")
  // reliably keeps the whole head in frame with headroom and the character
  // facing the viewer across diverse sheets (knight/android/beastkin/scholar);
  // the too-loose case is then tightened by the deterministic zoomToCharacter
  // crop. The skin branch tolerates upper-body input (img2skin's fallback
  // painter only samples dominant colors, not body geometry).
  //
  // Background is a softly blurred, in-context setting (NOT a flat color): the
  // shallow depth of field puts the character in sharp focus, which is the
  // sharp-vs-blurred contrast zoomToCharacter's focus-energy detector relies on.
  //
  // Personality line (Change 1): the sheet's tone drives expression/pose so a
  // "direct and candid" android doesn't render as a flustered blushing girl.
  // Beastkin get an explicit humanization clause: without it, style renders drew
  // a literal animal (full cat head, fur-covered body) instead of a person with
  // animal ears. "Front view, never seen from behind" exists because a beastkin
  // render (Anaya, wolf-person) came back as a full-body BACK view — the clause's
  // tail emphasis invites the model to turn the character around to show it.
  const beastkinClause =
    sheet.background === 'beastkin'
      ? ' Beastkin: fully human face and body with smooth human skin, absolutely no fur on the face or body; fur only on the animal ears and tail.'
      : '';
  const tone = String(sheet.personality?.tone ?? '').replace(/\s+/g, ' ').trim();
  const toneClause = tone ? ` Their expression, pose and body language convey: ${tone}.` : '';
  // Em/en dashes are stripped from the assembled prompt (sheet.image_prompt and
  // the tone are LLM-written and may contain them) — user copy standard, and the
  // image model reads a comma identically.
  const imagePrompt = (
    `${sheet.image_prompt}. One character, medium shot from the waist up. ` +
    'The entire head is fully visible with empty space above the head. ' +
    'The character faces the viewer and looks toward the camera. Not a close up of the face. ' +
    'Front view, never seen from behind. ' +
    'Background: a softly blurred, out of focus setting that fits the character, ' +
    'shallow depth of field. The character is in sharp focus.' +
    toneClause +
    beastkinClause
  ).replace(/\s*[—–]\s*/g, ', ');

  // ── Parallel: (portrait → skin) + persona expansion ────────────────────
  let portraitBytes: Buffer | null = null;
  let skinBytes: Buffer | null = null;
  let expanded: string | null = null;

  // The portrait/skin branch swallows its own failures — an image failure must
  // NEVER fail the whole generation (character saves with no portrait/skin).
  const portraitSkinBranch = (async (): Promise<void> => {
    emit('portrait', 'start');
    let rawPng: Buffer;
    try {
      rawPng = await generatePortraitPng(imagePrompt, styleId);
    } catch (err) {
      emit('portrait', 'error', err instanceof Error ? err.message : String(err));
      return; // no portrait, no skin
    }
    // Deterministic zoom-crop (character ≈ 75% of frame height). Best-effort:
    // returns rawPng unchanged when the focus detector isn't confident. BOTH
    // branches consume the crop — the tight framing also keeps the skin
    // painter's dominant-color sample off the blurred background.
    const cropped = await zoomToCharacter(rawPng);
    try {
      portraitBytes = await toCompliantPortraitPng(cropped);
      emit('portrait', 'done');
    } catch (err) {
      portraitBytes = null;
      emit('portrait', 'error', err instanceof Error ? err.message : String(err));
    }
    emit('skin', 'start');
    try {
      skinBytes = await rawPngToSkin(cropped, gender === 'female' ? 'slim' : 'classic', jwt);
      emit('skin', 'done');
    } catch (err) {
      skinBytes = null;
      emit('skin', 'error', err instanceof Error ? err.message : String(err));
    }
  })();

  // The persona branch is load-bearing — its failure fails the generation.
  const personaBranch = (async (): Promise<void> => {
    emit('persona', 'start');
    const { expandPersona } = await import('./personaExpansion');
    const { expanded: exp } = await expandPersona({
      name: sheet.name,
      source: blurb,
      cloudMode: { baseURL: `${PROXY_BASE_URL}/free`, authToken: jwt },
    });
    expanded = exp;
    emit('persona', 'done');
  })();

  const [, personaResult] = await Promise.allSettled([portraitSkinBranch, personaBranch]);
  if (personaResult.status === 'rejected' || expanded == null) {
    const reason =
      personaResult.status === 'rejected'
        ? (personaResult.reason instanceof Error ? personaResult.reason.message : String(personaResult.reason))
        : 'no persona produced';
    emit('persona', 'error', reason);
    return {
      ok: false,
      code: personaResult.status === 'rejected' ? classifyGenError(personaResult.reason) : 'generation_failed',
      message: `Couldn't write the companion's personality: ${reason}`,
    };
  }

  // ── Stage 'saving' — persist + apply portrait/skin + public_id fetch-back ─
  // The wall-clock cap already resolved the race with a failure once `signal`
  // is aborted — saving now would create an invisible orphan that eats a slot.
  if (signal.aborted) {
    return { ok: false, code: 'generation_failed', message: 'Generation timed out. Please try again.' };
  }
  emit('saving', 'start');
  const id = randomUUID();
  const now = new Date().toISOString();
  const character: Character = {
    id,
    kind: 'unique',
    public_id: null,
    name: sheet.name,
    persona: { source: blurb, expanded },
    is_default: false,
    shared: false,
    slug: null,
    metadata: {
      proactiveness: 1,
      // Texting register off the sheet (see Sheet.punctuation). Promoted to a
      // first-class metadata key — same forward-compat slot as proactiveness —
      // so the bot init + chat surface read it without digging into the sheet.
      punctuation: sheet.punctuation === 'deliberate' ? 'deliberate' : 'casual',
      soulcaster_sheet: sheet as unknown as Record<string, unknown>,
      // TTS voice for voice calls. metadata rides the cloud sync verbatim, so
      // the assignment follows the character across devices.
      ...(sheet.voice_id ? { voiceId: sheet.voice_id } : {}),
    },
    created: now,
    last_launched: null,
    playtime_ms: 0,
    portrait_image: null,
    skin: { source: 'none', mojang_username: null, png_sha256: null, applied_at: null },
    username: null,
    owner: userId,
    description,
  };

  const { saveCharacter, saveCharacterRaw, getCharacter, recordCreation } = await import('./characterStore');
  try {
    await saveCharacter(character);
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    emit('saving', 'error', msg);
    return { ok: false, code: 'generation_failed', message: `Couldn't save the companion: ${msg}` };
  }
  // Count the creation against the daily cap (MAX_CREATIONS_PER_DAY) now that
  // the character exists on disk — the guard-3 pre-check reads this log.
  await recordCreation();

  // Record the grant now that the cast is durably saved, so the next cast
  // moves down the ranking. Only RANKED preferences are recorded (random
  // rolls stay repeatable). updateConfig re-reads under the file lock and
  // re-checks membership against the CURRENT ranking — the `config` snapshot
  // this pipeline started from is minutes old by now (TOCTOU: the user may
  // have re-ranked mid-generation). Best-effort: a failed write means the
  // next cast repeats this dynamic, which beats failing a finished cast.
  try {
    const { updateConfig } = await import('./configStore');
    await updateConfig((cur) => {
      const ranked = cur.user_profile?.companion_dynamics ?? [];
      const granted = cur.dynamics_granted ?? [];
      if (!ranked.includes(dynamic) || granted.includes(dynamic)) return cur;
      return { ...cur, dynamics_granted: [...granted, dynamic] };
    });
  } catch (err) {
    console.warn(`[sei] gen: dynamics_granted update failed: ${(err as Error).message}`);
  }

  // Apply portrait + skin now that the character JSON exists on disk. Both are
  // best-effort — a failure here leaves the companion without art, never blocks.
  if (portraitBytes) {
    try {
      const { applyPortrait } = await import('./portraitStore');
      await applyPortrait({ characterId: id, bytes: portraitBytes });
    } catch (err) {
      emit('portrait', 'error', err instanceof Error ? err.message : String(err));
    }
  }
  if (skinBytes) {
    try {
      const { applyPng } = await import('./skinStore');
      await applyPng({ personaId: id, pngBytes: skinBytes, source: 'upload' });
    } catch (err) {
      emit('skin', 'error', err instanceof Error ? err.message : String(err));
    }
  }

  // public_id fetch-back — best-effort. Drain one sync op (the upsert enqueued
  // by saveCharacter) so the server assigns public_id, then read it back and
  // re-save locally via saveCharacterRaw (avoids re-enqueueing a mirror).
  try {
    const { processNext } = await import('./cloud/syncQueue');
    await processNext();
    const { getAuthedClient } = await import('./auth/supabaseClient');
    const { data } = await getAuthedClient(jwt)
      .from('characters')
      .select('public_id')
      .eq('id', id)
      .maybeSingle();
    const pub = (data as { public_id?: unknown } | null)?.public_id;
    if (typeof pub === 'string' && /^[A-Z0-9]{4}$/.test(pub)) {
      const latest = await getCharacter(id);
      if (latest) await saveCharacterRaw({ ...latest, public_id: pub });
    }
  } catch (err) {
    console.warn(`[sei] generateUnique public_id fetch-back failed for ${id}: ${(err as Error).message}`);
  }

  emit('saving', 'done');
  return { ok: true, characterId: id };
}
