/**
 * 260703 procgen — Unique-companion generation pipeline (MAIN process only).
 *
 * Orchestrates the full "Meet your unique companion" flow:
 *   soulcaster-1 character sheet  →  in PARALLEL { portrait (proxy image gen) →
 *   img2skin skin } + persona expansion  →  save (kind 'unique', shared false).
 *
 * Cloud-mode + signed-in only: the character sheet + persona both stream through
 * the proxy's `/free` route, and the portrait is generated by the proxy's
 * `/generate/image` endpoint (Bearer JWT). BYOK users cannot generate — they get
 * `not_signed_in`.
 *
 * The pipeline NEVER throws for expected failures; it resolves the discriminated
 * `GenerateUniqueResult`. Stage progress is pushed via the injected `emit` sink
 * (the IPC handler tags each tick with the caller's requestId and forwards it on
 * IpcChannel.gen.progress — same shape as chars:expansion-progress).
 *
 * Ordering note (deviation from the literal spec, functionally identical): the
 * expensive parallel work (image gen + img2skin + persona expansion) runs
 * concurrently and only PRODUCES bytes/text; the store writes (saveCharacter →
 * applyPortrait → applyPng) are serialized AFTER the character JSON exists on
 * disk. applyPortrait / applyPng both `getCharacter` + `saveCharacter`, so they
 * require the row to exist — saving first and applying after avoids a
 * skeleton-write race between the two branches.
 */

import { randomUUID } from 'node:crypto';
import { createRequire } from 'node:module';
import { mkdtemp, writeFile, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import Anthropic from '@anthropic-ai/sdk';
import type {
  GenerateUniqueInput,
  GenerateUniqueResult,
  GenStage,
  UniqueGender,
} from '../shared/ipc';
import type { Character, UserConfig, UserPreferences } from '../shared/characterSchema';
import { MAX_COMPANION_SLOTS } from '../shared/characterSchema';
import { PORTRAIT_MAX_BYTES, PORTRAIT_MAX_DIM } from './portraitImageUtil';
import { parsePngIhdr } from './skinImageUtil';

const PROXY_BASE_URL = process.env.SEI_PROXY_URL ?? 'https://api.sei.gg';

/** Model used for the soulcaster sheet consolidation call (proxy /free route). */
const SHEET_MODEL = 'claude-haiku-4-5';
const SHEET_TIMEOUT_MS = 60_000;
const IMAGE_TIMEOUT_MS = 60_000;
/** Overall wall-clock cap for the pipeline body (after the fast guards). */
const PIPELINE_CAP_MS = 150_000;

/** Progress sink: the IPC handler baked in the caller's requestId. */
export type GenEmit = (stage: GenStage, status: 'start' | 'done' | 'error', message?: string) => void;

/* -------------------------------------------------------------------------- */
/*  Pure helpers (unit-tested)                                                 */
/* -------------------------------------------------------------------------- */

/**
 * Number of Home companion slots the user currently occupies. MUST mirror the
 * renderer's Home/IconRail library filter, or the slot guard rejects on a
 * visibly non-full grid (and vice versa):
 *
 *   - bundled defaults (is_default) occupy a slot only when invited
 *     (config.added_default_ids);
 *   - FOREIGN-owned characters (owner set, !== current user) occupy a slot
 *     only when explicitly added from the World tab (config.added_world_ids).
 *     This matters because merely hovering/opening a World card caches the
 *     foreign row locally (charsOpenPrepare → ensureLocallyCached), so a bare
 *     `!is_default` count would inflate with every browse;
 *   - everything else (own + legacy null-owner local chars) always counts.
 */
export function libraryCharacterCount(
  characters: Pick<Character, 'id' | 'is_default' | 'owner'>[],
  config: { added_default_ids?: string[] | null; added_world_ids?: string[] | null },
  currentUserId: string | null = null,
): number {
  const addedDefaults = new Set(config.added_default_ids ?? []);
  const addedWorld = new Set(config.added_world_ids ?? []);
  let n = 0;
  for (const c of characters) {
    if (c.is_default) {
      if (addedDefaults.has(c.id)) n += 1;
    } else if (currentUserId && c.owner != null && c.owner !== currentUserId) {
      if (addedWorld.has(c.id)) n += 1;
    } else {
      n += 1;
    }
  }
  return n;
}

const EMPTY_PREFS: UserPreferences = {
  companion_age_range: null,
  art_style: null,
  completed_at: null,
};

/**
 * Reconcile the local (config.user_profile) and cloud (user_preferences row)
 * questionnaire copies. Cloud wins when it is NEWER — it carries a completed_at
 * that the local copy lacks, or a later completed_at.
 *
 *   - profile      — the effective profile to return to the renderer.
 *   - cloudIsNewer — true when the cloud copy should be written back into config.
 *   - hasCompleted — true when EITHER copy has a completed_at (drives `needed`:
 *                    the caller sets needed = signedIn && !hasCompleted).
 */
export function resolvePrefs(
  local: UserPreferences | null,
  cloud: UserPreferences | null,
): { profile: UserPreferences; cloudIsNewer: boolean; hasCompleted: boolean } {
  const localDone = !!local?.completed_at;
  const cloudDone = !!cloud?.completed_at;

  let cloudIsNewer = false;
  if (cloud && cloudDone) {
    if (!localDone) {
      cloudIsNewer = true;
    } else {
      const c = Date.parse(cloud.completed_at!);
      const l = Date.parse(local!.completed_at!);
      cloudIsNewer = Number.isFinite(c) && (!Number.isFinite(l) || c > l);
    }
  }

  const profile = cloudIsNewer
    ? cloud!
    : (local ?? cloud ?? EMPTY_PREFS);

  return { profile, cloudIsNewer, hasCompleted: localDone || cloudDone };
}

/** Rendering-style suffix appended to the sheet's image_prompt, per art_style. */
export function artStyleSuffix(artStyle: UserPreferences['art_style']): string {
  switch (artStyle) {
    case 'chibi':
      return 'round chibi style';
    case 'celshaded':
      return 'cel-shaded, Genshin Impact-like';
    case 'cartoon':
      return 'western cartoon style';
    case '3d':
      return 'high-quality stylized 3D render';
    case 'anime':
    case null:
    default:
      return 'anime style';
  }
}

/** Trim a paragraph down to its first `maxSentences` sentences / `maxChars`. */
function condense(text: string, maxSentences: number, maxChars: number): string {
  const clean = String(text ?? '').replace(/\s+/g, ' ').trim();
  if (!clean) return '';
  const sentences = clean.match(/[^.!?]+[.!?]+/g) ?? [clean];
  let out = sentences.slice(0, maxSentences).join(' ').trim();
  if (out.length > maxChars) out = out.slice(0, maxChars).trimEnd() + '…';
  return out;
}

type Sheet = {
  name: string;
  gender: string;
  age: number;
  age_note: string | null;
  background: string;
  species_detail: string;
  personality: { tone: string; values: string[]; quirks: string[]; fears: string[] };
  backstory: string;
  voice_style: string;
  appearance: Record<string, unknown>;
  image_prompt: string;
};

/**
 * Build a compact appearance/outfit summary from the sheet's `appearance`
 * block, or '' when there's nothing usable (defensive; soulcaster's schema
 * requires these fields, but older sheets / test fixtures may omit them).
 *
 * 260704: the sheet's appearance (incl. `outfit`, a specific, prompt-enforced
 * garment description) was being generated but never reaching the character's
 * persona/description — the LLM playing the companion had no idea what it
 * wore. This folds outfit + hair/eyes/height/build + accessories/distinguishing
 * features into one terse line so both `expandPersona` and the bot's runtime
 * persona know what the character looks like and is wearing.
 */
function buildAppearanceSummary(appearance: Record<string, unknown> | null | undefined): string {
  const a = appearance ?? {};
  const str = (v: unknown): string => (typeof v === 'string' ? v.trim() : '');
  const list = (v: unknown): string[] =>
    Array.isArray(v) ? v.filter((x): x is string => typeof x === 'string' && x.trim().length > 0) : [];
  const sentence = (s: string): string => (s === '' || /[.…]$/.test(s) ? s : `${s}.`);

  const overall = condense(str(a.overall), 1, 160);
  const outfit = condense(str(a.outfit), 2, 280);
  const hair = str(a.hair);
  const eyes = str(a.eyes);
  const heightBuild = [str(a.height), str(a.build)].filter(Boolean).join(', ');
  const accessories = list(a.accessories);
  const features = list(a.distinguishing_features);

  const bits: string[] = [];
  if (overall) bits.push(sentence(overall));
  if (outfit) bits.push(sentence(`Wears: ${outfit}`));
  if (hair) bits.push(sentence(`Hair: ${hair}`));
  if (eyes) bits.push(sentence(`Eyes: ${eyes}`));
  if (heightBuild) bits.push(sentence(heightBuild));
  if (accessories.length) bits.push(sentence(`Accessories: ${accessories.slice(0, 3).join(', ')}`));
  if (features.length) bits.push(sentence(`Features: ${features.slice(0, 2).join(', ')}`));

  return bits.join(' ');
}

/**
 * Compose the persona `source` blurb the expander consumes — a compact readable
 * paragraph (NOT raw JSON) covering identity, personality, voice, appearance
 * (incl. outfit), and a condensed backstory.
 */
export function buildPersonaBlurb(sheet: Sheet): string {
  const p = sheet.personality;
  const ageBit = sheet.age_note ? `${sheet.age} (${sheet.age_note})` : `${sheet.age}`;
  const species = sheet.species_detail || sheet.background;
  const appearanceSummary = buildAppearanceSummary(sheet.appearance);
  const lines = [
    `${sheet.name} — ${species}, age ${ageBit}.`,
    `Tone: ${sheet.personality.tone}`,
    `Values: ${(p.values ?? []).join(', ')}`,
    `Quirks: ${(p.quirks ?? []).join(', ')}`,
    `Fears: ${(p.fears ?? []).join(', ')}`,
    `Voice: ${sheet.voice_style}`,
    ...(appearanceSummary ? [`Appearance: ${appearanceSummary}`] : []),
    `Backstory: ${condense(sheet.backstory, 4, 600)}`,
  ];
  return lines.join('\n');
}

/**
 * Safety cap for `buildDescription`'s output. `Character.description` in
 * src/shared/characterSchema.ts is an UNBOUNDED `z.string()` — no `.max()` —
 * so nothing downstream enforces a length. soulcaster's prompt asks for a
 * 150-300 word backstory (prompt.js) but only Zod-validates `min(1)`, so a
 * misbehaving model could in principle return something far longer. This cap
 * (~300+ words of headroom) is therefore a defensive backstop, not a schema
 * requirement — under normal generation the full backstory always fits and
 * is used verbatim.
 */
const DESCRIPTION_MAX_CHARS = 2200;

/**
 * Trim `text` to at most `maxChars`, preferring a sentence boundary. Returns
 * the trimmed text plus whether any trimming occurred (the caller decides
 * whether to append an ellipsis — only meaningful when the cut lands
 * mid-thought, i.e. no sentence boundary was found to land on cleanly).
 */
function trimToSentenceBoundary(clean: string, maxChars: number): { text: string; truncated: boolean } {
  if (clean.length <= maxChars) return { text: clean, truncated: false };
  const sentences = clean.match(/[^.!?]+[.!?]+/g) ?? [clean];
  let out = '';
  for (const s of sentences) {
    if ((out + s).length > maxChars) break;
    out += s;
  }
  out = out.trim();
  if (out) return { text: out, truncated: true };
  // Not even the first sentence fits — hard cut.
  return { text: clean.slice(0, maxChars).trimEnd(), truncated: true };
}

/**
 * User-facing `description`: the soulcaster sheet's own backstory paragraph,
 * verbatim (whitespace-collapsed) when it fits. This IS the public-facing
 * text shown on the World tab / CharacterPage — the backstory is
 * prompt-enforced to explain how the character's look and personality
 * cohere, so it reads as a real description rather than a stat line.
 *
 * Falls back to the old `"{name}, a {species}. {first sentence}"` stat-line
 * format only when the backstory is missing/empty/whitespace — defensive,
 * since the soulcaster schema requires `backstory: z.string().min(1)`.
 */
export function buildDescription(sheet: Sheet): string {
  const clean = String(sheet.backstory ?? '').replace(/\s+/g, ' ').trim();
  if (clean) {
    const { text, truncated } = trimToSentenceBoundary(clean, DESCRIPTION_MAX_CHARS);
    return truncated ? `${text}…` : text;
  }
  const species = sheet.species_detail || sheet.background;
  const first = condense(sheet.backstory, 1, 160);
  const base = `${sheet.name}, a ${species}.`;
  const desc = first ? `${base} ${first}` : base;
  return desc.length > 220 ? desc.slice(0, 220).trimEnd() + '…' : desc;
}

/* -------------------------------------------------------------------------- */
/*  Runtime deps (image processing loaded lazily / defensively)               */
/* -------------------------------------------------------------------------- */

interface SharpLike {
  (input: Buffer): {
    resize(opts: { width: number; height: number; fit: 'inside'; withoutEnlargement?: boolean }): {
      png(opts: { compressionLevel?: number; palette?: boolean; colors?: number; quality?: number }): {
        toBuffer(): Promise<Buffer>;
      };
    };
  };
}

let _sharp: SharpLike | null | undefined;

/**
 * Load sharp WITHOUT taking a direct dependency on it: sharp ships as a
 * transitive dep of img2skin (which the skin pipeline resolves the same way).
 * Resolved from the img2skin package directory so it works in dev and in
 * asar-unpacked packaged builds. Returns null when sharp is unavailable — the
 * caller then only applies an already-compliant portrait.
 */
function loadSharp(): SharpLike | null {
  if (_sharp !== undefined) return _sharp;
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  const req = typeof require === 'function' ? require : createRequire(process.cwd() + '/');
  const tries: Array<() => string> = [
    () => req.resolve('sharp', { paths: [path.dirname(req.resolve('img2skin/package.json'))] }),
    () => req.resolve('sharp'),
  ];
  for (const resolve of tries) {
    try {
      _sharp = req(resolve()) as SharpLike;
      return _sharp;
    } catch {
      /* try next */
    }
  }
  _sharp = null;
  return _sharp;
}

/**
 * Coerce arbitrary generated PNG bytes into the portrait pipeline's constraints
 * (≤PORTRAIT_MAX_DIM² and ≤PORTRAIT_MAX_BYTES) so applyPortrait's validation
 * accepts them. Uses sharp (via img2skin) to progressively downscale + palette-
 * compress; falls back to the raw bytes only when they are already compliant.
 */
async function toCompliantPortraitPng(bytes: Buffer): Promise<Buffer> {
  let dims: { width: number; height: number } | null = null;
  try {
    dims = parsePngIhdr(bytes);
  } catch {
    dims = null;
  }
  const alreadyOk =
    bytes.length <= PORTRAIT_MAX_BYTES &&
    dims != null &&
    dims.width <= PORTRAIT_MAX_DIM &&
    dims.height <= PORTRAIT_MAX_DIM;
  if (alreadyOk) return bytes;

  const sharp = loadSharp();
  if (!sharp) {
    throw new Error('portrait exceeds limits and image processing (sharp) is unavailable');
  }
  for (const size of [PORTRAIT_MAX_DIM, 896, 768, 640, 512]) {
    const out = await sharp(bytes)
      .resize({ width: size, height: size, fit: 'inside', withoutEnlargement: true })
      .png({ compressionLevel: 9, palette: true, quality: 90 })
      .toBuffer();
    if (out.length <= PORTRAIT_MAX_BYTES) return out;
  }
  // Last resort — aggressive palette reduction at the smallest size.
  return await sharp(bytes)
    .resize({ width: 512, height: 512, fit: 'inside', withoutEnlargement: true })
    .png({ compressionLevel: 9, palette: true, colors: 128, quality: 70 })
    .toBuffer();
}

/**
 * Turn a full-body character PNG into a valid 64×64 Minecraft skin via
 * img2skin's deterministic 'fallback' branch (no API key required). Writes the
 * source + reads the skin through a scratch temp dir that is always cleaned up.
 *
 * `variant` selects the Minecraft skin model geometry — 'slim' (Alex, narrow
 * arms) vs 'classic' (Steve, wide arms). The bot serves skins via
 * CustomSkinLoader with model "auto", which detects slim vs classic from the
 * PNG's arm-region geometry, so passing the right variant here is what makes
 * female companions actually render as slim in-game (no schema/server change
 * needed).
 */
async function rawPngToSkin(rawPng: Buffer, variant: 'slim' | 'classic'): Promise<Buffer> {
  const dir = await mkdtemp(path.join(tmpdir(), 'sei-skin-'));
  const src = path.join(dir, 'character.png');
  const out = path.join(dir, 'skin.png');
  try {
    await writeFile(src, rawPng);
    const { characterToSkin } = await import('img2skin/src/pipeline.js');
    await characterToSkin(src, out, { branch: 'fallback', variant });
    return await readFile(out);
  } finally {
    await rm(dir, { recursive: true, force: true }).catch(() => {});
  }
}

/**
 * POST the proxy image-generation endpoint. Returns the raw PNG bytes.
 * 60s wall-clock timeout via AbortController.
 */
async function generatePortraitPng(prompt: string, jwt: string): Promise<Buffer> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), IMAGE_TIMEOUT_MS);
  try {
    const resp = await fetch(`${PROXY_BASE_URL}/generate/image`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${jwt}`,
      },
      body: JSON.stringify({ prompt }),
      signal: controller.signal,
    });
    if (!resp.ok) {
      throw new Error(`image generation failed: HTTP ${resp.status}`);
    }
    const json = (await resp.json()) as { png_base64?: unknown };
    const b64 = json?.png_base64;
    if (typeof b64 !== 'string' || b64.length === 0) {
      throw new Error('image generation failed: response missing png_base64');
    }
    return Buffer.from(b64, 'base64');
  } finally {
    clearTimeout(timer);
  }
}

/**
 * Build the soulcaster `llm` sink — an Anthropic call over the proxy's /free
 * route (mirrors personaExpansion's cloud wiring). Non-streaming; returns the
 * model's raw text for soulcaster to parse + validate.
 */
function buildSoulcasterLlm(jwt: string): (args: {
  system: string;
  user: string;
  maxTokens?: number;
}) => Promise<string> {
  // apiKey:null → no X-Api-Key header, only Authorization: Bearer <jwt>.
  const client = new Anthropic({
    baseURL: `${PROXY_BASE_URL}/free`,
    authToken: jwt,
    apiKey: null,
    maxRetries: 0,
  });
  return async ({ system, user, maxTokens }) => {
    const resp = await client.messages.create(
      {
        model: SHEET_MODEL,
        max_tokens: maxTokens ?? 4096,
        system,
        messages: [{ role: 'user', content: user }],
      },
      { timeout: SHEET_TIMEOUT_MS },
    );
    // Duck-type the first text block out of the response content (avoids
    // coupling to a specific SDK content-block union export).
    const content = (resp as { content?: unknown }).content;
    if (Array.isArray(content)) {
      for (const b of content) {
        if (
          b != null &&
          typeof b === 'object' &&
          (b as { type?: unknown }).type === 'text' &&
          typeof (b as { text?: unknown }).text === 'string'
        ) {
          return (b as { text: string }).text;
        }
      }
    }
    return '';
  };
}

/** Classify an error into a network vs. generic generation failure. */
function classifyGenError(err: unknown): 'network' | 'generation_failed' {
  const msg = (err instanceof Error ? err.message : String(err)).toLowerCase();
  if (/enotfound|enetunreach|getaddrinfo|dns|econnrefused|econnreset|offline|fetch failed|network|timed? ?out|aborted/i.test(msg)) {
    return 'network';
  }
  return 'generation_failed';
}

/* -------------------------------------------------------------------------- */
/*  Orchestrator                                                              */
/* -------------------------------------------------------------------------- */

export interface GenerateUniqueDeps {
  /** Stage-progress sink (requestId already baked in by the caller). */
  emit: GenEmit;
}

export async function generateUnique(
  input: GenerateUniqueInput,
  deps: GenerateUniqueDeps,
): Promise<GenerateUniqueResult> {
  const { emit } = deps;
  const gender: UniqueGender = input.gender;

  // ── Guard 1: signed-in + cloud backend ─────────────────────────────────
  const { getAiBackendKind } = await import('./apiKeyStore');
  const { getClient } = await import('./auth/supabaseClient');
  const backendKind = await getAiBackendKind();
  const session = (await getClient().auth.getSession()).data.session;
  const jwt = session?.access_token ?? null;
  const userId = session?.user?.id ?? null;
  if (!jwt || !userId) {
    return { ok: false, code: 'not_signed_in', message: 'Sign in to generate a unique companion.' };
  }
  if (backendKind !== 'cloud-proxy') {
    return {
      ok: false,
      code: 'not_signed_in',
      message: 'Switch to managed billing (cloud) to generate a unique companion.',
    };
  }

  // ── Guard 2: slot limit ────────────────────────────────────────────────
  const { loadConfig } = await import('./configStore');
  const { listCharacters } = await import('./characterStore');
  const config = await loadConfig();
  const characters = await listCharacters();
  if (libraryCharacterCount(characters, config, userId) >= MAX_COMPANION_SLOTS) {
    return {
      ok: false,
      code: 'slot_limit',
      message: `You can only have ${MAX_COMPANION_SLOTS} companions. Remove one to make room.`,
    };
  }

  // ── Guard 3: daily creation quota ──────────────────────────────────────
  const { checkCreateQuota } = await import('./characterStore');
  const quota = await checkCreateQuota();
  if (quota.blocked) {
    return {
      ok: false,
      code: 'daily_limit',
      message: 'Daily creation limit reached. Come back tomorrow to make another companion.',
    };
  }

  // Everything past the guards is bounded by the wall-clock cap. The cap ABORTS
  // the pipeline (checked before the save step) — a timed-out run must never
  // save an orphan companion the user was told failed, or a "Try again" would
  // mint a duplicate into a slot the orphan already consumed.
  const cap = new AbortController();
  const pipeline = runPipeline({ gender, jwt, userId, config, emit, signal: cap.signal });
  let capTimer: ReturnType<typeof setTimeout> | undefined;
  const capped = new Promise<GenerateUniqueResult>((resolve) => {
    capTimer = setTimeout(() => {
      cap.abort();
      resolve({ ok: false, code: 'generation_failed', message: 'Generation timed out. Please try again.' });
    }, PIPELINE_CAP_MS);
  });
  try {
    return await Promise.race([pipeline, capped]);
  } finally {
    clearTimeout(capTimer);
  }
}

async function runPipeline(args: {
  gender: UniqueGender;
  jwt: string;
  userId: string;
  config: UserConfig;
  emit: GenEmit;
  /** Set by the wall-clock cap: once aborted, the pipeline must not save. */
  signal: AbortSignal;
}): Promise<GenerateUniqueResult> {
  const { gender, jwt, userId, config, emit, signal } = args;

  // ── Stage 'sheet' — soulcaster consolidation ───────────────────────────
  let sheet: Sheet;
  emit('sheet', 'start');
  try {
    const { castSoul } = await import('soulcaster');
    const { sheet: cast } = await castSoul({
      gender,
      userProfile: config.user_profile ?? null,
      llm: buildSoulcasterLlm(jwt),
    });
    sheet = cast as Sheet;
    emit('sheet', 'done');
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    emit('sheet', 'error', msg);
    return { ok: false, code: classifyGenError(err), message: `Couldn't create the character sheet: ${msg}` };
  }

  const blurb = buildPersonaBlurb(sheet);
  const description = buildDescription(sheet);
  const imagePrompt =
    `${sheet.image_prompt} ${artStyleSuffix(config.user_profile?.art_style ?? null)}, ` +
    'full body, single character, standing, facing viewer, plain background';

  // ── Parallel: (portrait → skin) + persona expansion ────────────────────
  let portraitBytes: Buffer | null = null;
  let skinBytes: Buffer | null = null;
  let expanded: string | null = null;

  // The portrait/skin branch swallows its own failures — an image failure must
  // NEVER fail the whole generation (character saves with no portrait/skin).
  const portraitSkinBranch = (async (): Promise<void> => {
    emit('portrait', 'start');
    let rawPng: Buffer;
    try {
      rawPng = await generatePortraitPng(imagePrompt, jwt);
    } catch (err) {
      emit('portrait', 'error', err instanceof Error ? err.message : String(err));
      return; // no portrait, no skin
    }
    try {
      portraitBytes = await toCompliantPortraitPng(rawPng);
      emit('portrait', 'done');
    } catch (err) {
      portraitBytes = null;
      emit('portrait', 'error', err instanceof Error ? err.message : String(err));
    }
    emit('skin', 'start');
    try {
      skinBytes = await rawPngToSkin(rawPng, gender === 'female' ? 'slim' : 'classic');
      emit('skin', 'done');
    } catch (err) {
      skinBytes = null;
      emit('skin', 'error', err instanceof Error ? err.message : String(err));
    }
  })();

  // The persona branch is load-bearing — its failure fails the generation.
  const personaBranch = (async (): Promise<void> => {
    emit('persona', 'start');
    const { expandPersona } = await import('./personaExpansion');
    const { expanded: exp } = await expandPersona({
      name: sheet.name,
      source: blurb,
      cloudMode: { baseURL: `${PROXY_BASE_URL}/free`, authToken: jwt },
    });
    expanded = exp;
    emit('persona', 'done');
  })();

  const [, personaResult] = await Promise.allSettled([portraitSkinBranch, personaBranch]);
  if (personaResult.status === 'rejected' || expanded == null) {
    const reason =
      personaResult.status === 'rejected'
        ? (personaResult.reason instanceof Error ? personaResult.reason.message : String(personaResult.reason))
        : 'no persona produced';
    emit('persona', 'error', reason);
    return {
      ok: false,
      code: personaResult.status === 'rejected' ? classifyGenError(personaResult.reason) : 'generation_failed',
      message: `Couldn't write the companion's personality: ${reason}`,
    };
  }

  // ── Stage 'saving' — persist + apply portrait/skin + public_id fetch-back ─
  // The wall-clock cap already resolved the race with a failure once `signal`
  // is aborted — saving now would create an invisible orphan that eats a slot.
  if (signal.aborted) {
    return { ok: false, code: 'generation_failed', message: 'Generation timed out. Please try again.' };
  }
  emit('saving', 'start');
  const id = randomUUID();
  const now = new Date().toISOString();
  const character: Character = {
    id,
    kind: 'unique',
    public_id: null,
    name: sheet.name,
    persona: { source: blurb, expanded },
    is_default: false,
    shared: false,
    slug: null,
    metadata: { proactiveness: 1, soulcaster_sheet: sheet as unknown as Record<string, unknown> },
    created: now,
    last_launched: null,
    playtime_ms: 0,
    portrait_image: null,
    skin: { source: 'none', mojang_username: null, png_sha256: null, applied_at: null },
    username: null,
    owner: userId,
    description,
  };

  const { saveCharacter, saveCharacterRaw, getCharacter } = await import('./characterStore');
  try {
    await saveCharacter(character);
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    emit('saving', 'error', msg);
    return { ok: false, code: 'generation_failed', message: `Couldn't save the companion: ${msg}` };
  }

  // Apply portrait + skin now that the character JSON exists on disk. Both are
  // best-effort — a failure here leaves the companion without art, never blocks.
  if (portraitBytes) {
    try {
      const { applyPortrait } = await import('./portraitStore');
      await applyPortrait({ characterId: id, bytes: portraitBytes });
    } catch (err) {
      emit('portrait', 'error', err instanceof Error ? err.message : String(err));
    }
  }
  if (skinBytes) {
    try {
      const { applyPng } = await import('./skinStore');
      await applyPng({ personaId: id, pngBytes: skinBytes, source: 'upload' });
    } catch (err) {
      emit('skin', 'error', err instanceof Error ? err.message : String(err));
    }
  }

  // public_id fetch-back — best-effort. Drain one sync op (the upsert enqueued
  // by saveCharacter) so the server assigns public_id, then read it back and
  // re-save locally via saveCharacterRaw (avoids re-enqueueing a mirror).
  try {
    const { processNext } = await import('./cloud/syncQueue');
    await processNext();
    const { getAuthedClient } = await import('./auth/supabaseClient');
    const { data } = await getAuthedClient(jwt)
      .from('characters')
      .select('public_id')
      .eq('id', id)
      .maybeSingle();
    const pub = (data as { public_id?: unknown } | null)?.public_id;
    if (typeof pub === 'string' && /^[A-Z0-9]{4}$/.test(pub)) {
      const latest = await getCharacter(id);
      if (latest) await saveCharacterRaw({ ...latest, public_id: pub });
    }
  } catch (err) {
    console.warn(`[sei] generateUnique public_id fetch-back failed for ${id}: ${(err as Error).message}`);
  }

  emit('saving', 'done');
  return { ok: true, characterId: id };
}
